@startuml "RWA3 Class Diagram"
title RWA3 Class Diagram
skinparam ClassAttributeIconSize 0
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}


class Department {
    -employees_: std::set
    +display_employees()
    +add_employee()
}

class Date {
    -day_:unsigned short
    -month_:unsigned short
    -year_:unsigned short
    +is_valid_date(unsigned short day, unsigned short month, unsigned short year) bool const
    +get_days_in_month(unsigned short month, unsigned short year) unsigned short const
    +is_leap_year(unsigned short year) bool
    +Date(unsigned short d, unsigned short m, unsigned short y)
    +print_date() void const

}

class IDBadge{
    -badge_number_:std::string
    -issue_date:Date 
    +void display_badge_info()
}

class Manager {
    -team_size_: int
    -number_of_projects_: int
    +perform_task()
    +attend_meeting()
    +recieve_salary()
    +void conduct_performance_review()
    

}

class Developer{
    -programming_languages_:std::unordered_set
    -current_project_:std::string
    +perform_task()
    +attend_meeting()
    +recieve_salary()
    +void write_code(const std::string&)
    +void add_programming_language(const std::string&)
    +void set_current_project(const std::string&)
}

'Employee class
class Employee {
    -name_:std::string
    -salary_: int
    -IDBadge
    +perform_task()
    +attend_meeting()
    +recieve_salary()

}

'Relationships
Department "1" o-- "1..*" Employee : manages <<shared>>
Employee "1" o-- "1.." IDBadge : is assigned <<shared>>
IDBadge "1" O-- "1.." Date : issued on <<shared>>
Employee <|-- Developer: <<public>>
Employee <|-- Manager: <<public>>


@enduml